# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
starplus = TvChannel.create(name: "StarPlus")
  starplus.tv_shows.create(name: 'Krishna Chali London', timing: '23:30')
  starplus.tv_shows.create(name: 'Kullfi Kumarr Bajewala', timing: '23:00')
  starplus.tv_shows.create(name: 'Mariam Khan - Reporting Live', timing: '22:30')
  starplus.tv_shows.create(name: 'Ye Hai Mohabbatein', timing: '22:00')
  starplus.tv_shows.create(name: 'Nazar', timing: '21:30')
  starplus.tv_shows.create(name: 'Ishqbaaaz', timing: '21:00')
  starplus.tv_shows.create(name: 'Yeh Rishta Kya Kehlata Hai', timing: '20:30')
  starplus.tv_shows.create(name: 'Krishna Chali London', timing: '20:00')
  starplus.tv_shows.create(name: 'Kullfi Kumarr Bajewala', timing: '19:30')
  starplus.tv_shows.create(name: 'Mariam Khan - Reporting Live', timing: '19:00')
  starplus.tv_shows.create(name: 'Ye Hai Mohabbatein', timing: '18:30')
  starplus.tv_shows.create(name: 'Kasautii Zindagii Kay', timing: '18:00')
  starplus.tv_shows.create(name: 'Karnsangini', timing: '17:30')
  starplus.tv_shows.create(name: 'Nazar', timing: '17:00')
  starplus.tv_shows.create(name: 'Yeh Rishta Kya Kehlata Hai', timing: '04:30')

colors = TvChannel.create(name: "Colors")
  colors.tv_shows.create(name: 'Vidya', timing: '19:00')
  colors.tv_shows.create(name: 'Choti Sardaarni', timing: '19:30')
  colors.tv_shows.create(name: 'Shakti-Astitva ke Ehsaas Ki', timing: '20:00')
  colors.tv_shows.create(name: 'Luv Kush', timing: '20:30')
  colors.tv_shows.create(name: 'Gatbandhan', timing: '21:00')
  colors.tv_shows.create(name: 'Bahu Begum', timing: '21:30')
  colors.tv_shows.create(name: 'Bepanah', timing: '20:30')

sonytv = TvChannel.create(name: "Sony TV")
  sonytv.tv_shows.create(name: 'Mere Sai', timing: '19:00')
  sonytv.tv_shows.create(name: 'Vighnaharta Ganesh', timing: '19:30')
  sonytv.tv_shows.create(name: 'Ishaaron Ishaaron Mein', timing: '20:00')
  sonytv.tv_shows.create(name: 'Patiala Babes', timing: '20:30')
  sonytv.tv_shows.create(name: 'Kaun Banega Crorepati 11', timing: '21:00')
  sonytv.tv_shows.create(name: 'Mere Dad ki Dulhan', timing: '22:00')
  sonytv.tv_shows.create(name: 'Tara From Satara', timing: '22:30')